### PR TITLE
Add deformable conv to repo

### PR DESCRIPTION
**Pull request by Kracozebr**
Tried my best to add deformable conv to yolact edge. Unfortunately I have not have enough gpu to train on coco or over dataset to test metrics.

### CODE REVIEW

**Comment by haotian-liu** [comment]
Thank you so much for the contribution!  I will take a look at this soon -- we need to check on the compatibility with the new torch2trt dynamic plugin with the existing configurations, as well as its affect on the speed.  Thanks!

**Comment by Kracozebr** [comment]
> Thank you so much for the contribution! I will take a look at this soon -- we need to check on the compatibility with the new torch2trt dynamic plugin with the existing configurations, as well as its affect on the speed. Thanks!

Thanks, wait for your response! =)

**Comment by haotian-liu** [comment]
Thank you so much for your effort and sincerely apologize for the late follow-up as I have been working on a lot of other things :(

Your contribution has been merged :)

**Comment by haotian-liu** [comment]
Hi, as reported in #225, I noticed that the rock dataset was set as the default, causing the visualizations to break.  I have temporarily reverted this change as a fix.  I'll double check and add back the deformable conv feature to the repo later.
If you have time, it'd be very much appreciated if you could help make this change too.
Thank you again for your contributions.

**Comment by Kracozebr** [comment]
Hi, I turned out that I forgot to delete my dataset from config file, I made one more commit with fixes of config.py. What is the best way to add commit to pr?

**Comment by haotian-liu** [comment]
Maybe you can create a new pull request by first reverting this reversion commit (05db000bcfa09318d32e56a85ddf91059be8d4d8)?  And then make the modification.  Please let me know if this makes sense.

**Pull request merged**
