### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by linukc**
Hi @haotian-liu. I find it helpful to add a docker support for your great work.
I've only tested the _python train.py ..._ part (2x RTX 2080 TI + RTX 2070).
Now i am looking for a better way to add _tensorrt_ support.

### CODE REVIEW

**Comment by linukc** [comment]
- [ ] Add tensorrt and torch2trt
- [ ] Test pytorch from pip on several video cards

**Comment by haotian-liu** [comment]
Thank you for your effort! Having Docker will definitely allow the community a lot more ease to use the code base. I will take a look into this later this week.

**Comment by linukc** [comment]
For the build, I used [nvidia as default docker runtime.](https://stackoverflow.com/questions/59691207/docker-build-with-nvidia-runtime)

**Comment by linukc** [comment]
I have successfully trained and evaluated my own dataset using --disabled tensorrt based on 399b9c0. The next step is tensorrt.

**Comment by haotian-liu** [comment]
Thank you! This sounds great! I believe for TensorRT, it should be evaluting with an extra command line option without re-training. Hope everything works.

**Comment by linukc** [comment]
I have successfully transferred model to tensorrt with `--use_fp16_tensorrt` and `--use_tensorrt_safe_mode` (https://github.com/haotian-liu/yolact_edge/issues/96 without safe mode). So I can recommend you to accept my work. Soon I add README to describe basic usage.

**Comment by haotian-liu** [comment]
Hi, thank you for your hard work. I made several changes into the Dockerfile to (1) fix issues on GUI interface and locale; (2) adjust environment settings so that all the command can be used as [README.md](README.md) without any modifications.
If you have any suggestions and concerns, please let me know, thanks!

**Pull request merged**
