### PR TITLE
packaging & programmatic inference

### PR DESCRIPTION
**Pull request by simutisernestas**
PR for packaging and portable inference interface for external usage of YOLACT edge. There are still some unknowns to finalize this, so I would like to hear your opinion. I've tried to minimize the number of changes as much as possible to make merging smoother.

Firstly, those relative imports are a bit ugly and they could be replaced by absolute imports. In any case, one problem arises because of the imports (relative or absolute). If you try to launch the evaluation script as described in the README python interpreter says: ```ImportError: attempted relative import with no known parent package```. This could be easily solved by:

1) Installing the package first ```pip install .```
2) Replacing ```python eval.py ...``` by ```python -m yolact_edge.eval ...```

For example:

```python eval.py --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --image=my_image.png``` 

would become:

```python -m yolact_edge.eval --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --image=my_image.png```

Besides that, the core of the package is not modified in any way, and performance is not affected by these changes. 

The README includes an example of an external interface. Would be nice to hear your suggestions, corrections, or improvements in order to merge it.

### CODE REVIEW

**Comment by haotian-liu** [comment]
Hi, thank you for the brilliant contribution. This is really impressive. Regarding what you mentioned about the relative import, since I am not very familiar with packaging, could you elaborate more, or point me to some materials to gain some basic knowledge?
I believe it will be better not to have train.py / eval.py as part of the package. For the core functions or even wrap some of the operations in train.py / eval.py into the package, and put the APIs of train.py / eval.py as what they are. This makes sure: (1) all the users that are using the YolactEdge right now will not be affected at all; (2) one can load the model from the package, and do the inference (e.g. using `model(data)`, and data is prepared separately by standalone applications that are using the package).
Not sure if my understandings are correct, and please correct me if they are wrong. Thanks!

**Comment by simutisernestas** [comment]
Sorry for the late response. Relative import tells where to find the imported file relative to the file in consideration. The alternative would be to make them absolute and replace dots with ```yolact_edge``` in this case. But still, that requires first installing the package to be able to launch even train.py / eval.py scripts. So you would like to see them working without pre-installing the package first?

**Comment by haotian-liu** [comment]
@simutisernestas I am thinking in this way: if the installed package named `yolact_edge`, we put all of the packaged files in `yolact_edge` sub-directory. In train.py or eval.py, we import Yolact from yolact_edge. This is similar to that of detectron2. This makes sure that it works either with or without installing the package.

**Comment by simutisernestas** [comment]
That sounds great. Would you like me to do so? If you would re-open the PR I could add those changes.

**Comment by simutisernestas** [comment]
@haotian-bot any thoughts on this?

**Comment by haotian-liu** [comment]
I will create another branch for this, so that it will be easier to develop and merge.

**Comment by haotian-liu** [comment]
Please create a PR over branch `packaging_dev`, and we can work on it.

**Pull request merged**
