### PR TITLE
Added Dockerfile for Jetson AGX Xavier

### PR DESCRIPTION
**Pull request by akaneko1019**
Jetson needed an L4T image, so I created a Dockerfile using the L4T image.

### CODE REVIEW

**Comment by haotian-liu** [comment]
Thank you so much for your contribution!  There are some comments in Japanese characters which might not be quite intuitive for other users who are not familiar with Japanese.  Would you mind changing it to English?  Thanks!

**Comment by akaneko1019** [comment]
Sorry. I've changed the language from Japanese to English.
Please let me know if you have trouble understanding.

**Comment by akaneko1019** [comment]
How about after that?

**Comment by haotian-liu** [comment]
I am sorry that I was busying working on my other projects and maybe missed the email.  Thank you so much for your contribution and effort!  I will merge it now.

**Pull request merged**
